"use client";

import { useMemo, useState } from "react";
import { IconDownload, IconPhoto, IconFileSpreadsheet, IconFileDescription, IconDots, IconSearch, IconUpload } from "@tabler/icons-react";
import { useDocuments, useProjects, useTeamMembers } from "@/lib/use-data";
import { Avatar, Badge, Button, Card, Input, Select, Table, Td, Th } from "@/components/ui";

const icons={pdf:IconFileDescription,image:IconPhoto,doc:IconFileDescription,spreadsheet:IconFileSpreadsheet};
export function DocumentsView(){const [query,setQuery]=useState("");const [type,setType]=useState("all");const [projectId,setProjectId]=useState("all");const { documents } = useDocuments();const { projects } = useProjects();const { teamMembers } = useTeamMembers();const filtered=useMemo(()=>documents.filter(d=>(type==="all"||d.type===type)&&(projectId==="all"||d.projectId===projectId)&&d.name.toLowerCase().includes(query.toLowerCase())),[query,type,projectId,documents]);return <><div className="mb-5 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row"><div className="relative flex-1"><IconSearch className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search files..."/></div><Select value={type} onChange={e=>setType(e.target.value)}><option value="all">All file types</option><option value="pdf">PDF</option><option value="image">Images</option><option value="doc">Documents</option><option value="spreadsheet">Spreadsheets</option></Select><Select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="all">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Button><IconUpload className="size-4"/>Upload file</Button></div><Card className="overflow-hidden"><Table><thead><tr><Th>Name</Th><Th>Project</Th><Th>Uploaded by</Th><Th>Date</Th><Th>Size</Th><Th></Th></tr></thead><tbody>{filtered.map(doc=>{const Icon=icons[doc.type];const project=projects.find(p=>p.id===doc.projectId)!;const uploader=teamMembers.find(m=>m.id===doc.uploadedBy)!;return <tr key={doc.id} className="hover:bg-slate-50/70"><Td><div className="flex min-w-64 items-center gap-3"><span className={`flex size-10 items-center justify-center rounded-xl ${doc.type==="spreadsheet"?"bg-emerald-50 text-emerald-600":doc.type==="image"?"bg-violet-50 text-violet-600":"bg-red-50 text-red-600"}`}><Icon className="size-5"/></span><div><p className="font-medium text-slate-900">{doc.name}</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">{doc.type}</p></div></div></Td><Td>{project?.name ?? "—"}</Td><Td>{uploader ? <div className="flex items-center gap-2"><Avatar name={uploader.name} size="sm"/><span className="text-sm">{uploader.name}</span></div> : <span className="text-sm text-slate-400">—</span>}</Td><Td className="text-sm text-slate-500">{doc.uploadedAt}</Td><Td className="text-sm text-slate-500">{(doc.sizeKb/1024).toFixed(1)} MB</Td><Td><Button variant="ghost" size="icon"><IconDots className="size-4"/></Button></Td></tr>})}</tbody></Table></Card></>;}
