"use client";

import { useMemo, useState } from "react";
import { Download, FileImage, FileSpreadsheet, FileText, MoreHorizontal, Search, Upload } from "lucide-react";
import { documents, projects, teamMembers } from "@/lib/mock-data";
import { Avatar, Badge, Button, Card, Input, Select, Table, Td, Th } from "@/components/ui";

const icons={pdf:FileText,image:FileImage,doc:FileText,spreadsheet:FileSpreadsheet};
export function DocumentsView(){const [query,setQuery]=useState("");const [type,setType]=useState("all");const [projectId,setProjectId]=useState("all");const filtered=useMemo(()=>documents.filter(d=>(type==="all"||d.type===type)&&(projectId==="all"||d.projectId===projectId)&&d.name.toLowerCase().includes(query.toLowerCase())),[query,type,projectId]);return <><div className="mb-5 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search files..."/></div><Select value={type} onChange={e=>setType(e.target.value)}><option value="all">All file types</option><option value="pdf">PDF</option><option value="image">Images</option><option value="doc">Documents</option><option value="spreadsheet">Spreadsheets</option></Select><Select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="all">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Button><Upload className="size-4"/>Upload file</Button></div><Card className="overflow-hidden"><Table><thead><tr><Th>Name</Th><Th>Project</Th><Th>Uploaded by</Th><Th>Date</Th><Th>Size</Th><Th></Th></tr></thead><tbody>{filtered.map(doc=>{const Icon=icons[doc.type];const project=projects.find(p=>p.id===doc.projectId)!;const uploader=teamMembers.find(m=>m.id===doc.uploadedBy)!;return <tr key={doc.id} className="hover:bg-slate-50/70"><Td><div className="flex min-w-64 items-center gap-3"><span className={`flex size-10 items-center justify-center rounded-xl ${doc.type==="spreadsheet"?"bg-emerald-50 text-emerald-600":doc.type==="image"?"bg-violet-50 text-violet-600":"bg-red-50 text-red-600"}`}><Icon className="size-5"/></span><div><p className="font-medium text-slate-900">{doc.name}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-slate-400">{doc.type}</p></div></div></Td><Td><Badge className="normal-case"><i className="mr-1.5 size-2 rounded-full" style={{backgroundColor:project.color}}/>{project.name}</Badge></Td><Td><div className="flex items-center gap-2"><Avatar name={uploader.name} size="sm"/><span>{uploader.name}</span></div></Td><Td>{doc.uploadedAt}</Td><Td>{doc.sizeKb>1024?`${(doc.sizeKb/1024).toFixed(1)} MB`:`${doc.sizeKb} KB`}</Td><Td><div className="flex"><Button variant="ghost" size="icon"><Download className="size-4"/></Button><Button variant="ghost" size="icon"><MoreHorizontal className="size-4"/></Button></div></Td></tr>})}</tbody></Table></Card></>}
