"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, Grid2X2, List, MapPin, Plus, Search } from "lucide-react";
import { projects, teamMembers } from "@/lib/mock-data";
import { ProjectCard } from "@/components/page-elements";
import { Avatar, AvatarStack, Badge, Button, Dialog, Input, Label, Progress, Select, Table, Td, Textarea, Th } from "@/components/ui";
import { formatCurrency } from "@/lib/utils";

function NewProjectForm() { return <form className="grid gap-4" onSubmit={(e)=>e.preventDefault()}><div><Label>Project name</Label><Input placeholder="e.g. Downtown Commons"/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Client</Label><Input placeholder="Client organization"/></div><div><Label>Location</Label><Input placeholder="City, State"/></div></div><div><Label>Description</Label><Textarea placeholder="Short project summary..."/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Start date</Label><Input type="date"/></div><div><Label>Target completion</Label><Input type="date"/></div></div><div><Label>Estimated budget</Label><Input type="number" placeholder="$0"/></div><div className="flex justify-end gap-2 pt-2"><Button variant="outline" type="button">Save draft</Button><Button type="submit">Create project</Button></div></form>; }

export function ProjectsView() {
  const [view,setView]=useState<"grid"|"table">("grid"); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all");
  const filtered=useMemo(()=>projects.filter(p=>(status==="all"||p.status===status)&&`${p.name} ${p.client} ${p.location}`.toLowerCase().includes(query.toLowerCase())),[query,status]);
  return <><div className="mb-5 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, clients, locations..." className="border-0 bg-slate-50 pl-9 focus:bg-white"/></div><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="planning">Planning</option><option value="in_progress">In progress</option><option value="on_hold">On hold</option><option value="completed">Completed</option></Select><div className="flex rounded-lg border border-slate-200 p-1"><Button onClick={()=>setView("grid")} variant={view==="grid"?"secondary":"ghost"} size="icon" className="size-8"><Grid2X2 className="size-4"/></Button><Button onClick={()=>setView("table")} variant={view==="table"?"secondary":"ghost"} size="icon" className="size-8"><List className="size-4"/></Button></div><Dialog trigger={<Button><Plus className="size-4"/>New project</Button>} title="Create a new project" description="Add the core project details. You can complete the setup later."><NewProjectForm/></Dialog></div>
  <div className="mb-4 flex items-center justify-between text-xs text-slate-500"><span>{filtered.length} projects</span><span>Updated 8 minutes ago</span></div>
  {view==="grid"?<div className="grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{filtered.map(p=><ProjectCard project={p} key={p.id}/>)}</div>:<div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><Table><thead><tr><Th>Project</Th><Th>Status</Th><Th>Progress</Th><Th>Budget</Th><Th>Manager & team</Th><Th>Timeline</Th></tr></thead><tbody>{filtered.map(p=>{const manager=teamMembers.find(m=>m.id===p.managerId)!; const names=p.teamIds.map(id=>teamMembers.find(m=>m.id===id)!.name); return <tr key={p.id} className="hover:bg-slate-50/70"><Td><Link href={`/projects/${p.id}`} className="block"><p className="font-semibold text-slate-900 hover:text-orange-600">{p.name}</p><p className="mt-1 flex items-center gap-1 text-xs"><MapPin className="size-3"/>{p.location}</p></Link></Td><Td><Badge value={p.status}/></Td><Td><div className="w-32"><div className="mb-1 flex justify-between text-xs"><span>{p.progress}%</span></div><Progress value={p.progress}/></div></Td><Td><p className="font-medium text-slate-900">{formatCurrency(p.budget,true)}</p><p className="mt-1 text-xs">{formatCurrency(p.spent,true)} spent</p></Td><Td><div className="flex items-center gap-3"><Avatar name={manager.name} size="sm"/><AvatarStack names={names} limit={3}/></div></Td><Td><p className="flex items-center gap-1.5 text-xs"><CalendarDays className="size-3.5"/>{p.endDate}</p></Td></tr>})}</tbody></Table></div>}
  {filtered.length===0&&<div className="rounded-xl border border-dashed border-slate-300 bg-white py-20 text-center"><p className="font-medium text-slate-800">No matching projects</p><p className="mt-1 text-sm text-slate-500">Try a different search or filter.</p></div>}</>;
}
