"use client";

import Link from "next/link";
import { IconArrowLeft, IconCalendarMonth, IconMapPin, IconUsers } from "@tabler/icons-react";
import { useOperations } from "@/components/operations-provider";
import { KanbanBoard } from "@/components/kanban-board";
import { ProjectDetailTimeline } from "@/components/project-detail-timeline";
import { Avatar, Badge, Card, CardContent, Progress, Tabs } from "@/components/ui";

export function ProjectDetailView({ projectId }: { projectId: string }) {
  const { snapshot, loading, error } = useOperations();
  const project = snapshot.projects.find((item) => item.id === projectId);
  if (loading) return <Card className="p-16 text-center text-sm text-slate-500">Loading live project…</Card>;
  if (!project) return <Card className="p-16 text-center"><p className="font-semibold text-slate-900">Project not found</p><Link href="/projects" className="mt-3 inline-block text-sm text-orange-600">Back to projects</Link></Card>;
  const tasks = snapshot.tasks.filter((task) => task.projectId === project.id);
  const assignedIds = new Set(tasks.map((task) => task.assigneeId).filter(Boolean));
  const members = snapshot.technicians.filter((member) => assignedIds.has(member.id) || member.id === project.managerId);
  const overview = <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-6"><Card><CardContent><h3 className="font-semibold text-slate-950">Project overview</h3><p className="mt-3 text-sm leading-6 text-slate-600">{project.description || "No project description."}</p><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">{[["Crew assigned", members.length], ["Open tasks", tasks.filter((task) => task.state !== "COMPLETE" && task.state !== "FAILED").length], ["Overall progress", `${project.progress}%`], ["Target completion", project.endDate || "Not set"]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1.5 font-bold text-slate-950">{value}</p></div>)}</div></CardContent></Card><Card><CardContent><div className="flex items-center justify-between"><h3 className="font-semibold text-slate-950">DAG completion</h3><span className="text-2xl font-bold text-orange-600">{project.progress}%</span></div><Progress value={project.progress} className="mt-6 h-3" /></CardContent></Card></div><Card><CardContent><h3 className="font-semibold text-slate-950">Operations team</h3><div className="mt-4 space-y-4">{members.map((member) => <div key={member.id} className="flex items-center gap-3"><Avatar name={member.name} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{member.name}</p><p className="text-xs text-slate-500">{member.role}</p></div><Badge value={member.status} /></div>)}</div>{!members.length && <p className="mt-4 text-sm text-slate-500">No technicians assigned.</p>}</CardContent></Card></div>;
  const activity = <Card><CardContent><h3 className="font-semibold text-slate-950">Backend activity</h3><div className="mt-4 space-y-3">{snapshot.taskEvents.filter((event) => tasks.some((task) => task.id === event.taskId)).slice(0, 30).map((event) => <div key={event.id} className="rounded-lg border border-slate-100 p-3"><div className="flex items-center gap-2"><Badge value={event.newState.toLowerCase()} /><span className="text-xs font-medium text-slate-800">{tasks.find((task) => task.id === event.taskId)?.title || event.taskId}</span></div><p className="mt-2 text-xs text-slate-500">{event.reason}</p><p className="mt-1 text-[10px] text-slate-400">{new Date(event.createdAt).toLocaleString()} · depth {event.depth}</p></div>)}</div></CardContent></Card>;
  return <><Link href="/projects" className="mb-4 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-orange-600"><IconArrowLeft className="size-3.5" />Back to projects</Link>{error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-bold text-slate-950">{project.name}</h2><Badge value={project.status} /></div><p className="mt-2 text-sm text-slate-500">{project.client}</p><div className="mt-4 flex flex-wrap gap-6 text-xs text-slate-500"><span className="flex items-center gap-1.5"><IconMapPin className="size-4" />{project.location}</span><span className="flex items-center gap-1.5"><IconCalendarMonth className="size-4" />{project.startDate || "Unscheduled"} – {project.endDate || "Unscheduled"}</span><span className="flex items-center gap-1.5"><IconUsers className="size-4" />{members.length} assigned</span></div></div><Tabs useHash tabs={[{ value: "overview", label: "Overview", content: overview }, { value: "schedule", label: "DAG Board", content: <KanbanBoard projectId={project.id} /> }, { value: "timeline", label: "Timeline", content: <ProjectDetailTimeline projectId={project.id} /> }, { value: "activity", label: "Activity", content: activity }]} /></>;
}
