"use client";

import { useState } from "react";
import { Check } from "lucide-react";
import { Avatar, Button, Card, CardContent, Input, Label, Select, Tabs, Textarea } from "@/components/ui";

function SaveButton(){const [saved,setSaved]=useState(false);return <Button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}>{saved?<><Check className="size-4"/>Saved</>:"Save changes"}</Button>}
const profile=<Card><CardContent className="max-w-2xl"><div className="mb-6 flex items-center gap-4"><Avatar name="Marcus Chen" size="xl"/><div><Button variant="outline" size="sm">Change photo</Button><p className="mt-2 text-xs text-slate-400">JPG or PNG. Max 2 MB.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>First name</Label><Input defaultValue="Marcus"/></div><div><Label>Last name</Label><Input defaultValue="Chen"/></div><div><Label>Email</Label><Input type="email" defaultValue="marcus@syncfield.co"/></div><div><Label>Phone</Label><Input defaultValue="(415) 555-0183"/></div><div className="sm:col-span-2"><Label>Job title</Label><Input defaultValue="Project Director"/></div><div className="sm:col-span-2"><Label>Bio</Label><Textarea defaultValue="Construction operations leader focused on predictable delivery and collaborative field teams."/></div></div><div className="mt-6 flex justify-end"><SaveButton/></div></CardContent></Card>;
const company=<Card><CardContent className="max-w-2xl"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Company name</Label><Input defaultValue="SyncField Construction Group"/></div><div><Label>Company email</Label><Input defaultValue="operations@syncfield.co"/></div><div><Label>Phone</Label><Input defaultValue="(415) 555-0100"/></div><div className="sm:col-span-2"><Label>Address</Label><Input defaultValue="220 Howard Street, San Francisco, CA 94105"/></div><div><Label>Time zone</Label><Select className="w-full" defaultValue="pacific"><option value="pacific">Pacific Time (PT)</option><option>Mountain Time (MT)</option><option>Central Time (CT)</option></Select></div><div><Label>Currency</Label><Select className="w-full"><option>USD — US Dollar</option></Select></div></div><div className="mt-6 flex justify-end"><SaveButton/></div></CardContent></Card>;
const notifications=<Card><CardContent className="max-w-2xl"><div className="space-y-1">{[{title:"Task assignments",desc:"When a task is assigned to you"},{title:"Project updates",desc:"Daily digest for projects you manage"},{title:"Budget alerts",desc:"When a cost code exceeds 90% utilization"},{title:"Document activity",desc:"When documents need your review"},{title:"Daily log reminders",desc:"At 4:00 PM on active site days"}].map((item,i)=><label key={item.title} className="flex cursor-pointer items-center justify-between rounded-lg p-3 hover:bg-slate-50"><div><p className="text-sm font-medium text-slate-900">{item.title}</p><p className="mt-0.5 text-xs text-slate-500">{item.desc}</p></div><input type="checkbox" defaultChecked={i!==3} className="size-4 accent-orange-500"/></label>)}</div><div className="mt-6 flex justify-end"><SaveButton/></div></CardContent></Card>;
export function SettingsView(){return <Tabs tabs={[{value:"profile",label:"Profile",content:profile},{value:"company",label:"Company",content:company},{value:"notifications",label:"Notifications",content:notifications}]}/>}
