"use client";

import { useMemo, useState } from "react";
import { IconMail, IconPhone, IconPlus, IconSearch } from "@tabler/icons-react";
import { useProjects, useTeamMembers } from "@/lib/use-data";
import { Avatar, Badge, Button, Card, CardContent, Dialog, Input, Label, Select } from "@/components/ui";

function InviteForm({ projects }: { projects: { id: string; name: string }[] }) {
  return <form className="space-y-4" onSubmit={e=>e.preventDefault()}><div className="grid gap-4 sm:grid-cols-2"><div><Label>First name</Label><Input placeholder="First name"/></div><div><Label>Last name</Label><Input placeholder="Last name"/></div></div><div><Label>Work email</Label><Input type="email" placeholder="name@company.com"/></div><div><Label>Role</Label><Select className="w-full"><option>Site Manager</option><option>Engineer</option><option>Foreperson</option><option>Subcontractor</option></Select></div><div><Label>Assign to project</Label><Select className="w-full">{projects.map(p=><option key={p.id}>{p.name}</option>)}</Select></div><Button type="submit" className="w-full">Send invitation</Button></form>;
}
export function TeamView(){const [query,setQuery]=useState(""); const [role,setRole]=useState("all"); const { teamMembers } = useTeamMembers(); const { projects } = useProjects(); const roles=[...new Set(teamMembers.map(m=>m.role))]; const filtered=useMemo(()=>teamMembers.filter(m=>(role==="all"||m.role===role)&&`${m.name} ${m.role}`.toLowerCase().includes(query.toLowerCase())),[query,role,teamMembers]); return <><div className="mb-5 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-3 sm:flex-row"><div className="relative flex-1"><IconSearch className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" placeholder="Search team members..." value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</Select><Dialog trigger={<Button><IconPlus className="size-4"/>Invite member</Button>} title="Invite a team member" description="They'll receive an email with access instructions."><InviteForm projects={projects} /></Dialog></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{filtered.map(member=><Card key={member.id} className="transition-shadow hover:shadow-md"><CardContent><div className="flex items-start justify-between"><Avatar name={member.name} size="xl"/><Badge value={member.status}/></div><h3 className="mt-4 font-semibold text-slate-950">{member.name}</h3><p className="mt-1 text-sm text-slate-500">{member.role}</p><div className="mt-4 space-y-2 border-t border-slate-100 pt-4 text-xs text-slate-500"><p className="flex items-center gap-2"><IconMail className="size-3.5"/>{member.email}</p><p className="flex items-center gap-2"><IconPhone className="size-3.5"/>{member.phone}</p></div><div className="mt-4 flex flex-wrap gap-1">{member.projectIds.map(id=><Badge key={id}>{projects.find(p=>p.id===id)?.name.split(" ")[0]}</Badge>)}</div></CardContent></Card>)}</div></>;}
