import { notFound } from "next/navigation";
import { IconArrowLeft, IconCalendarMonth, IconSun, IconDownload, IconPhoto, IconFileSpreadsheet, IconFileDescription, IconHelmet, IconMapPin, IconDots, IconPencil, IconPlus, IconUpload, IconUsers } from "@tabler/icons-react";
import Link from "next/link";
import { documents, projects, subtasks, tasks, teamMembers } from "@/lib/mock-data";
import { Avatar, Badge, Button, Card, CardContent, Progress, Table, Tabs, Td, Th } from "@/components/ui";

export function generateStaticParams() { return projects.map(({id})=>({id})); }

const fileIcon = { pdf:IconFileDescription, image:IconPhoto, doc:IconFileDescription, spreadsheet:IconFileSpreadsheet };

export default async function ProjectDetailPage({ params }: { params: Promise<{ id:string }> }) {
  const { id } = await params; const project=projects.find(p=>p.id===id); if(!project) notFound();
  const projectTasks=tasks.filter(t=>t.projectId===project.id); const projectDocs=documents.filter(d=>d.projectId===project.id); const members=project.teamIds.map(memberId=>teamMembers.find(m=>m.id===memberId)!).filter(Boolean);
  const overview=<div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-6"><Card><CardContent><h3 className="font-semibold text-slate-950">Project overview</h3><p className="mt-3 text-sm leading-6 text-slate-600">{project.description}</p><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">{[["Crew assigned",members.length.toString()],["Open tasks",projectTasks.filter(t=>t.status!=="done").length.toString()],["Overall progress",`${project.progress}%`],["Target completion",project.endDate]].map(([label,value])=><div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1.5 font-bold text-slate-950">{value}</p></div>)}</div></CardContent></Card><Card><CardContent><div className="flex items-center justify-between"><div><h3 className="font-semibold text-slate-950">Construction progress</h3><p className="mt-1 text-xs text-slate-500">Current phase: Structural & envelope</p></div><span className="text-2xl font-bold text-orange-600">{project.progress}%</span></div><Progress value={project.progress} className="mt-6 h-3"/><div className="mt-6 grid grid-cols-4 gap-1">{["Foundation","Structure","Envelope","Interiors"].map((phase,i)=><div key={phase}><div className={`mb-2 h-1 rounded-full ${i<2?"bg-emerald-500":i===2?"bg-orange-500":"bg-slate-200"}`}/><p className="text-[10px] text-slate-500">{phase}</p></div>)}</div></CardContent></Card></div><Card><CardContent><h3 className="font-semibold text-slate-950">Project team</h3><div className="mt-4 space-y-4">{members.slice(0,5).map(member=><div key={member.id} className="flex items-center gap-3"><Avatar name={member.name}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{member.name}</p><p className="text-xs text-slate-500">{member.role}</p></div><span className="size-2 rounded-full bg-emerald-500"/></div>)}</div><Button variant="outline" className="mt-4 w-full">View all team members</Button></CardContent></Card></div>;

  const columns=[{key:"todo",label:"To do"},{key:"in_progress",label:"In progress"},{key:"review",label:"Review"},{key:"done",label:"Done"}] as const;
  const schedule=<div className="grid gap-4 xl:grid-cols-4">{columns.map(column=><div key={column.key} className="rounded-xl bg-slate-100/70 p-3"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${column.key==="done"?"bg-emerald-500":column.key==="review"?"bg-violet-500":column.key==="in_progress"?"bg-orange-500":"bg-slate-400"}`}/><h3 className="text-sm font-semibold text-slate-800">{column.label}</h3><span className="text-xs text-slate-400">{projectTasks.filter(t=>t.status===column.key).length}</span></div><IconPlus className="size-4 text-slate-400"/></div><div className="space-y-3">{projectTasks.filter(t=>t.status===column.key).map(task=>{const assignee=teamMembers.find(m=>m.id===task.assigneeId)!; const taskSubtasks=subtasks.filter(st=>st.taskId===task.id); return <Card key={task.id} className="shadow-sm hover:border-slate-300"><CardContent className="p-4"><div className="flex items-start justify-between gap-2"><Badge value={task.priority}/><IconDots className="size-4 text-slate-400"/></div><p className="mt-3 text-sm font-semibold leading-5 text-slate-900">{task.title}</p>{taskSubtasks.length>0&&<div className="mt-3 space-y-1.5 border-t border-slate-100 pt-3">{taskSubtasks.map(st=>{const stAssignee=teamMembers.find(m=>m.id===st.assigneeId); return <div key={st.id} className="flex items-center gap-2 text-xs"><span className={`size-1.5 rounded-full shrink-0 ${st.status==="done"?"bg-emerald-500":"bg-slate-300"}`}/><span className={`${st.status==="done"?"line-through text-slate-400":"text-slate-700"}`}>{st.title}</span>{stAssignee&&<span className="ml-auto shrink-0 text-slate-400">{stAssignee.name.split(" ")[0]}</span>}</div>})}</div>}<div className="mt-4 flex items-center justify-between"><Avatar name={assignee.name} size="sm"/><span className="flex items-center gap-1 text-[11px] text-slate-500"><IconCalendarMonth className="size-3"/>{task.dueDate}</span></div></CardContent></Card>})}</div></div>)}</div>;

  const documentView=<Card className="overflow-hidden"><div className="flex items-center justify-between p-5"><div><h3 className="font-semibold text-slate-950">Project files</h3><p className="mt-1 text-xs text-slate-500">{projectDocs.length} files in this workspace</p></div><Button><IconUpload className="size-4"/>Upload</Button></div><Table><thead><tr><Th>Name</Th><Th>Uploaded by</Th><Th>Date</Th><Th>Size</Th><Th></Th></tr></thead><tbody>{projectDocs.map(doc=>{const Icon=fileIcon[doc.type], uploader=teamMembers.find(m=>m.id===doc.uploadedBy)!; return <tr key={doc.id}><Td><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-orange-50 text-orange-600"><Icon className="size-4"/></span><span className="font-medium text-slate-900">{doc.name}</span></div></Td><Td><div className="flex items-center gap-2"><Avatar name={uploader.name} size="sm"/>{uploader.name}</div></Td><Td>{doc.uploadedAt}</Td><Td>{(doc.sizeKb/1024).toFixed(1)} MB</Td><Td><Button variant="ghost" size="icon"><IconDownload className="size-4"/></Button></Td></tr>})}</tbody></Table></Card>;

  const teamView=<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{members.map(member=><Card key={member.id}><CardContent className="flex items-center gap-4"><Avatar name={member.name} size="lg"/><div className="min-w-0"><h3 className="truncate font-semibold text-slate-950">{member.name}</h3><p className="mt-1 text-sm text-slate-500">{member.role}</p><p className="mt-2 truncate text-xs text-slate-400">{member.email}</p></div></CardContent></Card>)}</div>;

  const logs=[{date:"June 20, 2026",weather:"68°F · Partly cloudy",crew:42,note:"Level 14 concrete pour started at 07:15. No safety incidents. Curtain wall delivery received and inventoried."},{date:"June 19, 2026",weather:"66°F · Clear",crew:38,note:"MEP rough-in continued on levels 10–12. City inspector approved fire-stopping mockup."},{date:"June 18, 2026",weather:"63°F · Light rain",crew:31,note:"Exterior work paused from 10:30–13:00 due to weather. Interior framing remained on schedule."}];
  const logsView=<div className="mx-auto max-w-3xl space-y-4">{logs.map((log,i)=><div className="relative flex gap-4" key={log.date}><div className="flex flex-col items-center"><span className="flex size-10 items-center justify-center rounded-full bg-orange-50 text-orange-600 ring-4 ring-slate-50"><IconHelmet className="size-4"/></span>{i<logs.length-1&&<span className="h-full w-px bg-slate-200"/>}</div><Card className="mb-2 flex-1"><CardContent><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold text-slate-950">{log.date}</h3><Badge>Submitted</Badge></div><div className="mt-4 flex flex-wrap gap-4 text-xs text-slate-500"><span className="flex items-center gap-1.5"><IconSun className="size-4"/>{log.weather}</span><span className="flex items-center gap-1.5"><IconUsers className="size-4"/>{log.crew} crew on site</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{log.note}</p></CardContent></Card></div>)}</div>;

  return <><Link href="/projects" className="mb-4 inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-orange-600"><IconArrowLeft className="size-3.5"/>Back to projects</Link><div className="mb-6 flex flex-col justify-between gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-bold tracking-tight text-slate-950">{project.name}</h2><Badge value={project.status}/></div><p className="mt-2 text-sm text-slate-500">{project.client}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span className="flex items-center gap-1.5"><IconMapPin className="size-4"/>{project.location}</span><span className="flex items-center gap-1.5"><IconCalendarMonth className="size-4"/>{project.startDate} — {project.endDate}</span></div></div><Button variant="outline"><IconPencil className="size-4"/>Edit project</Button></div><Tabs tabs={[{value:"overview",label:"Overview",content:overview},{value:"schedule",label:"Schedule / Tasks",content:schedule},{value:"documents",label:"Documents",content:documentView},{value:"team",label:"Team",content:teamView},{value:"logs",label:"Daily Logs",content:logsView}]}/></>;
}
